
package br.edu.ifsul.lpoo.cs.gui.usuario;

import br.edu.ifsul.cs.Controle;
import java.awt.CardLayout;

public class JPanelJogador extends javax.swing.JPanel {

    private JPanelListagem listagem;
    private JPanelEdicao edicao;
    private Controle controle;
    
    public JPanelListagem getListagem() {
        return listagem;
    }

    public void setListagem(JPanelListagem listagem) {
        this.listagem = listagem;
    }

    public JPanelEdicao getEdicao() {
        return edicao;
    }

    public void setEdicao(JPanelEdicao edicao) {
        this.edicao = edicao;
    }

    public Controle getControle() {
        return controle;
    }

    public void setControle(Controle controle) {
        this.controle = controle;
    }
    
    
    public JPanelJogador(Controle controle) {
        this.controle = controle;
        
        initComponents();
        
        listagem = new JPanelListagem(this);
        edicao = new JPanelEdicao(this);
        
        //inclusao das duas telas
        this.add(listagem, "tela_listagem");
        this.add(edicao, "tela_edicao");
        
        showTela("tela_listagem");
    }
    /*funcao para exibir as telas*/
    public void showTela(String nome){
        if(nome.equals("tela_listagem")){
            listagem.populaTable();
        } else if(nome.equals("tela_edicao")){
            edicao.populaComboTipoArma();//carrega as Tipo arma no combox
            edicao.populaComboMunicao();//carrega as Municao no combox
            
        }
        CardLayout cl = (CardLayout) this.getLayout();
        cl.show(this, nome);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
